#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.lite.yml}"
JOB_HINT="${1:-}"
SAVEPOINT_PATH="${2:-}"
SAVEPOINT_PATH_FILE="${SAVEPOINT_PATH_FILE:-.ops-r2-last-savepoint}"
INIT_SQL="/workspace/labs/04-flink-paimon/00-init-flink-session.sql"
INIT_SQL_HOST="labs/04-flink-paimon/00-init-flink-session.sql"

if [[ -z "${SAVEPOINT_PATH}" && -f "${SAVEPOINT_PATH_FILE}" ]]; then
  SAVEPOINT_PATH="$(tr -d '[:space:]' < "${SAVEPOINT_PATH_FILE}")"
fi

if [[ -z "${JOB_HINT}" || -z "${SAVEPOINT_PATH}" ]]; then
  echo "Usage: $0 <ingest-ux-events|ingest-review-current|ingest-order-current> [savepoint-path]" >&2
  echo "If savepoint-path is omitted, ${SAVEPOINT_PATH_FILE} is used." >&2
  exit 2
fi

case "${JOB_HINT}" in
  ingest-ux-events|ux|append)
    SQL_FILE_HOST="labs/04-flink-paimon/13a-insert-olist-ux-events-streaming.sql"
    RESTORE_FILE_HOST="labs/04-flink-paimon/.restore-ux-events.sql"
    RESTORE_FILE_CONTAINER="/workspace/labs/04-flink-paimon/.restore-ux-events.sql"
    ;;
  ingest-review-current|review|review_current)
    SQL_FILE_HOST="labs/04-flink-paimon/13b-insert-olist-review-current-streaming.sql"
    RESTORE_FILE_HOST="labs/04-flink-paimon/.restore-review-current.sql"
    RESTORE_FILE_CONTAINER="/workspace/labs/04-flink-paimon/.restore-review-current.sql"
    ;;
  ingest-order-current|order|order_current)
    SQL_FILE_HOST="labs/04-flink-paimon/13c-insert-olist-order-current-streaming.sql"
    RESTORE_FILE_HOST="labs/04-flink-paimon/.restore-order-current.sql"
    RESTORE_FILE_CONTAINER="/workspace/labs/04-flink-paimon/.restore-order-current.sql"
    ;;
  *)
    echo "Unknown job hint: ${JOB_HINT}" >&2
    exit 2
    ;;
esac

cleanup() {
  rm -f "${RESTORE_FILE_HOST}"
}
trap cleanup EXIT

{
  echo "-- Generated by ops-r2-restore-job-from-savepoint.sh"
  echo "SET 'execution.savepoint.path' = '${SAVEPOINT_PATH}';"
  echo
  cat "${SQL_FILE_HOST}"
} > "${RESTORE_FILE_HOST}"

echo "Restoring ${JOB_HINT} from savepoint:"
echo "  ${SAVEPOINT_PATH}"

docker compose -f "${COMPOSE_FILE}" cp \
  "${INIT_SQL_HOST}" \
  "flink-jobmanager:${INIT_SQL}"
docker compose -f "${COMPOSE_FILE}" cp \
  "${RESTORE_FILE_HOST}" \
  "flink-jobmanager:${RESTORE_FILE_CONTAINER}"

docker compose -f "${COMPOSE_FILE}" exec -T --user flink flink-jobmanager \
  /opt/flink/bin/sql-client.sh \
  -i "${INIT_SQL}" \
  -f "${RESTORE_FILE_CONTAINER}"

echo
echo "Check the restored job:"
echo "  ./scripts/ops-flink-list-jobs.sh"
