#!/usr/bin/env bash
set -euo pipefail

# R5b: recover the emptied/corrupted Iceberg mart by rolling back to a known-good
# snapshot, instead of re-deriving it through Airflow (R5).
#
# Rebuild (R5)  : re-derive the mart from upstream (Paimon) via Airflow. Authoritative,
#                 slower, needs the source to still be correct.
# Rollback (R5b): move the table pointer back to a previous snapshot. Instant, but it
#                 discards everything committed after that snapshot, so only use it when
#                 that is what you actually want.
#
# Get the snapshot_id from:
#   ./scripts/ops-r5-find-iceberg-recovery-point.sh

COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.lite.yml}"
TABLE="${TABLE:-analytics.olist_category_daily}"
SNAPSHOT_ID="${1:-}"

if [[ -z "${SNAPSHOT_ID}" ]]; then
  echo "Usage: $0 <snapshot_id>" >&2
  echo "Find a recovery-point snapshot_id first:" >&2
  echo "  ./scripts/ops-r5-find-iceberg-recovery-point.sh" >&2
  exit 2
fi

GENERATED_SQL_HOST="$(mktemp -t r5b-rollback.XXXXXX.sql)"
GENERATED_SQL_CONTAINER="/tmp/r5b-rollback.sql"

cleanup() {
  rm -f "${GENERATED_SQL_HOST}"
}
trap cleanup EXIT

cat > "${GENERATED_SQL_HOST}" <<SQL
-- Generated by ops-r5b-rollback-iceberg-mart.sh
SELECT COUNT(*) AS row_count_before_rollback FROM iceberg_lake.${TABLE};
CALL iceberg_lake.system.rollback_to_snapshot('${TABLE}', ${SNAPSHOT_ID});
SELECT COUNT(*) AS row_count_after_rollback FROM iceberg_lake.${TABLE};
SQL

echo "Rolling back iceberg_lake.${TABLE} to snapshot ${SNAPSHOT_ID} ..."
# Copy the generated SQL into the container (mount-layout independent), make it readable
# by the spark user (docker cp lands it root-owned), then run it.
docker compose -f "${COMPOSE_FILE}" cp "${GENERATED_SQL_HOST}" "spark-client:${GENERATED_SQL_CONTAINER}"
docker compose -f "${COMPOSE_FILE}" exec -T --user root spark-client chmod 644 "${GENERATED_SQL_CONTAINER}"
docker compose -f "${COMPOSE_FILE}" exec -T spark-client \
  /workspace/scripts/spark-iceberg-sql-inner.sh "${GENERATED_SQL_CONTAINER}"

echo
echo "Rolled back via metadata pointer (no recompute from source)."
echo "Verify the serving layer sees it too:"
echo "  ./scripts/query-iceberg-tables.sh"
echo "  ./scripts/query-bi-metrics.sh"
echo
echo "Note: rollback discards snapshots committed after ${SNAPSHOT_ID}. If you instead want"
echo "the authoritative re-derived mart, recover through Airflow (R5):"
echo "  ./scripts/trigger-airflow-pipeline.sh"
