-- Deprecated aggregate entrypoint.
--
-- The original version of this file submitted three RUNNING Flink jobs from one
-- SQL file. That made it harder to stop/savepoint/restore one ingestion path at
-- a time. The streaming ingestion SQL is now split by job:
--
--   13a-insert-olist-ux-events-streaming.sql
--   13b-insert-olist-review-current-streaming.sql
--   13c-insert-olist-order-current-streaming.sql
--
-- Use the script below instead of running this file directly:
--
--   ./scripts/run-flink-olist-paimon-streaming.sh
